### PR TITLE
Automatically roll latest version tag

### LINKED ISSUE #27: Unable to resolve action `game-ci/steam-deploy@v1`, unable to find version `v1`
**Bug description**

I see v1.0 has been tagged recently, so I expected to be able to reference the action as described in the README using `game-ci/steam-deploy@v1`, however as the title suggests this fails to be found.

**How to reproduce**

Use a workflow that has a step with:

```
      - uses: game-ci/steam-deploy@v1
```

**Expected behavior**

It should resolve to the commit tagged with v1.0.

### PR DESCRIPTION
**Pull request by davidmfinol**
#### Changes

- Automatically roll v1 whenever a new release tag is published. Closes #27.

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Review by webbertakken — APPROVED** [review]
Yup

**Comment by webbertakken** [comment]
Didn't seem to work after editing the release, even though reading the [triggers documentation](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release) I had expected this to work.

**Comment by webbertakken** [comment]
Trying to fix in https://github.com/game-ci/steam-deploy/pull/30

**Comment by webbertakken** [comment]
Reverted in https://github.com/game-ci/steam-deploy/pull/31

Rolling next minor version instead.

**Comment by webbertakken** [comment]
Still does not work, with the warning `This action can only operate on semantically versioned releases`, however we probably don't want to publish patch level for a simple action like this.

I also do not see a difference in unity builder's [versioning workflow](https://github.com/game-ci/unity-builder/blob/main/.github/workflows/versioning.yml), just that we use a more complicated tag (`v2.0-alpha-13`) there. Which technically is also not a 3 digit semantic version either.

I believe 2 digit versions are quite common in actions, not sure if we should switch everything to 3 digit semantic versioning.
Any thoughts?

**Comment by davidmfinol** [comment]
I think we should use 3 digit semantic versioning everywhere, where we leave the patch version as 0 most of the time.

For example, can we try `v1.2.0` and see if that works? 
If it does, we could have the next release be `v1.3.0` and so on.

**Comment by webbertakken** [comment]
https://www.npmjs.com/package/semver#user-content-coercion should work for us.

However it is currently only done for prereleases (see [here](https://github.com/Actions-R-Us/actions-tagger/blob/8082799423f3a68e8e1f4b9f2606ca6c8f558ec4/src/functions.ts#L50)).

To make it work for non-prerelease v[Major].[Minor] and deduce [Patch] we will need this.

Forking the action.

**Comment by webbertakken** [comment]
> I think we should use 3 digit semantic versioning everywhere, where we leave the patch version as 0 most of the time.
> 
> For example, can we try `v1.2.0` and see if that works? If it does, we could have the next release be `v1.3.0` and so on.

Or that.

**Comment by webbertakken** [comment]
Since [rule 2](https://semver.org/#spec-item-2) of semantic versioning dictates that a normal version number MUST have three digits, I think your suggestion is better @davidmfinol.

Let's move to full semver for all our repos to solve the problem across the board.

Tagging one additional version to close this issue.

**Pull request merged**
