### PR TITLE
Exclude Unity's *_DoNotShip directory when uploading to Steam

### PR DESCRIPTION
**Pull request by bilalakil**
#### Changes

As discussed in #21

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated)
- [x] Tests (not needed)

### CODE REVIEW

**Comment by bilalakil** [comment]
I'd appreciate a sanity check that this actually works for someone else before merging 😛

**Review by webbertakken — APPROVED** [review]
LGTM

**Comment by bilalakil** [comment]
Cool so what happens next? 😛 I can't merge it myself

**Review by davidmfinol — APPROVED** [review]

**Comment by davidmfinol** [comment]
At the very least, this doesn't break anything for me, so I went ahead and merged.

For my project, however, there is no `{currentDepotPath}_BurstDebugInformation_DoNotShip` folder. The Unity folder that I remove is `{currentDepotPath}_BackUpThisFolder_ButDontShipItWithYourGame`. We might want to add that as well.

**Pull request merged**
