### PR TITLE
Exclude another Unity folder: `${currentDepotPath}_BackUpThisFolder_ButDontShipItWithYourGame`

### PR DESCRIPTION
**Pull request by bilalakil**
#### Changes

- Exclude the `${currentDepotPath}_BackUpThisFolder_ButDontShipItWithYourGame` directory that was mentioned after #22 was merged

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated)
- [x] Tests (not needed)

### CODE REVIEW

**Comment by bilalakil** [comment]
Thanks for mentioning this folder @davidmfinol - I was thinking the BurstDebug one that I first excluded didn't match my memory 🤔 I guess it differs between Unity versions now.

Are you able to confirm the functionality with this folder?

**Comment by davidmfinol** [comment]
For my windows builds, I actually use a custom build name, in which case, the path looks like this: `StandaloneWindows/cgs_BackUpThisFolder_ButDontShipItWithYourGame`.
Maybe we can make the pattern look like `$currentDepotPath/*_BackUpThisFolder_ButDontShipItWithYourGame*` to account for this? Could do the same for `BurstDebugInformation_DoNotShip`?

**Comment by webbertakken** [comment]
Sounds like we need something like a `gitignore` file, but for deploying to marketplaces.

**Comment by webbertakken** [comment]
Yea if these wildcards work it would be rather perfect.

Also note that not all glob matchers accept `**/` so keeping `depotpath` as part of the path might be needed.

**Comment by bilalakil** [comment]
I tried a few options and, interestingly, all 3 of them work:

```
  "FileExclusion" "**/*_BackUpThisFolder_ButDontShipItWithYourGame*"
  "FileExclusion" "*/*_BackUpThisFolder_ButDontShipItWithYourGame*"
  "FileExclusion" "$currentDepotPath/*_BackUpThisFolder_ButDontShipItWithYourGame*"
```

Any preferences?

I'd personally pick the first one because it's a more conventional glob format so the intention maybe comes across more clearly? Very light preference though.

I've updated the commit to match my recommendation so if there's no disagreement it can be merged once approved - but still happy to change it per other recommendations.

**Comment by webbertakken** [comment]
I'm fine with your preference as well. Let's go with that.

**Review by davidmfinol — APPROVED** [review]

**Pull request merged**
