### PR TITLE
feat(inputs): totp support

### LINKED ISSUE #17: Support Steam totp
**Context**

Basic Steam security, where a user has an MFA code sent over email, currently works.
However, some users may upgrade their Steam account to require MFA codes from a mobile authenticator.
The [CyberAndrii/steam-totp](https://github.com/CyberAndrii/steam-totp) action can also generate this MFA code, and we should support being able to accept this.

**Suggested solution**

Add `mfaCode` as an input. If `mfaCode` is input into the action, `configVdf`, `ssfnFileName`, and `ssfnFileContents` should all be ignored.

**Considered alternatives**

Could call it `totp` instead of `mfaCode`. I'm not sure which name would be clearer.

**Additional details**

See for more context: https://github.com/game-ci/steam-deploy/issues/4

### PR DESCRIPTION
**Pull request by eyzi**
#### Changes

- totp support (resolves #17)

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated)
- [x] Tests (passing on project: https://github.com/moonlitworks/without-romance/actions/runs/3193422828)

### CODE REVIEW

**Review by davidmfinol — APPROVED** [review]
Thanks for this! Can you check if it works with https://github.com/game-ci/steam-deploy/pull/46 too?

**Comment by eyzi** [comment]
> Thanks for this! Can you check if it works with #46 too?

Tested on a successful build (https://github.com/moonlitworks/without-romance/actions/runs/3210733592/jobs/5248407873) rebased on #46

Though, a few notes:
- I find that totp doesn't work when used twice, so i had test login only happen when it is using mfa files
- I removed the post-entrypoint from #46 as (a) the unescaped double quotes lead to `docker: invalid reference format` and (b) even with the double quotes escaped, it doesn't seem to locate `$(pwd)/manifest.vdf` correctly. Instead, I had to set output inside the main entrypoint

ref of changes: https://github.com/eyzi/steam-deploy/commits/timewarpinc 

Let me know if there are any issues with these. Thanks!

**Comment by webbertakken** [comment]
Could you be a bit more specific about the ref of your changes? It's showing all your commits.

**Comment by eyzi** [comment]
> Could you be a bit more specific about the ref of your changes? It's showing all your commits.

- Rebased this pr on #46 to test if this works with that, as per @davidmfinol's request
- Moved test login inside the else block to only run it when it is using mfa files
- Attempted to fix docker error by escaping double quotes in post-entrypoint
- Removed post-entrypoint entirely and set action output from the main entrypoint

**Pull request merged**
